services:
  aznum2words-webapp:
    build:
      context: .
      dockerfile: webapp.Dockerfile
    #    image: "aznum2words:0.0.1"
    restart: on-failure
    pull_policy: always
    networks:
      - aznum2words-network
    ports:
      - "8080:${APP_PORT}"
      - "9090:${METRIC_PORT}"
    environment:
      - DEPLOY_ENV=TEST
      - APP_PORT=8080
      - METRIC_PORT=9090
networks:
  aznum2words-network:
    ipam:
      driver: default